[[tasks]]
id = "hello_user"
server_id = "local"
shell_id = "powershell"
command_id = "echo_hello_user"
timeout = 30

[[tasks]]
id = "show_time"
server_id = "local"
shell_id = "powershell"
command_id = "echo_datetime"
timeout = 30

[[tasks]]
id = "join_done"
server_id = "local"
shell_id = "powershell"
command_id = "after_join"
timeout = 30
