#!/usr/bin/env bash
# Start an OpenSSH server in Docker, wait until the published port answers, then write
# constants.toml for use with graph_run --constants (e.g. ${TEST_SSH_HOST} in other TOML).
#
# Defaults are dev-only. Do not reuse passwords from this script in production.
#
# Usage:
#   ./scripts/docker-ssh-test-up.sh
#   SSH_USER=deploy SSH_PASSWORD='hunter2' HOST_PORT=2222 OUTPUT=./my-constants.toml ./scripts/docker-ssh-test-up.sh
#
# Tear down: ./scripts/docker-ssh-test-down.sh (same CONTAINER_NAME if you overrode it).
#
# Key-based login (PASSWORD_ACCESS=false on the image side):
#   SSH_PUBLIC_KEY_FILE=~/.ssh/id_ed25519.pub SSH_PASSWORD= ./scripts/docker-ssh-test-up.sh
#
# Environment:
#   CONTAINER_NAME   docker container name (default: graph_run_ssh_test)
#   SSH_USER         Linux account inside the container (default: testuser)
#   SSH_PASSWORD     login password when not using a key (default: testpass)
#   SSH_PUBLIC_KEY_FILE  if set, contents are passed to the image as PUBLIC_KEY; if SSH_PASSWORD
#                      is empty, PASSWORD_ACCESS is set to false
#   HOST_PORT        host TCP port mapped to sshd in the container (default: 2222)
#   OUTPUT           path to write TOML (default: constants.toml in cwd)
#   IMAGE            image ref (default: lscr.io/linuxserver/openssh-server:latest)
#   PREFER_CONTAINER_IP  if set to 1, TEST_SSH_HOST is the container bridge IP (often works on
#                      Linux Docker; Docker Desktop on macOS/Windows usually needs 127.0.0.1 + PORT)
#
set -euo pipefail

CONTAINER_NAME="${CONTAINER_NAME:-graph_run_ssh_test}"
SSH_USER="${SSH_USER:-testuser}"
SSH_PASSWORD="${SSH_PASSWORD:-testpass}"
HOST_PORT="${HOST_PORT:-2222}"
OUTPUT="${OUTPUT:-constants.toml}"
IMAGE="${IMAGE:-lscr.io/linuxserver/openssh-server:latest}"
PREFER_CONTAINER_IP="${PREFER_CONTAINER_IP:-0}"

escape_toml_basic() {
  # Escape for TOML double-quoted strings.
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

wait_for_tcp() {
  local host=$1
  local port=$2
  local max=${3:-60}
  local i=0
  while (( i < max )); do
    if bash -c "echo >/dev/tcp/${host}/${port}" 2>/dev/null; then
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  echo "timeout: nothing listening on ${host}:${port} after ${max}s" >&2
  return 1
}

PUBLIC_KEY_CONTENT=""
if [[ -n "${SSH_PUBLIC_KEY_FILE:-}" ]]; then
  if [[ ! -f "$SSH_PUBLIC_KEY_FILE" ]]; then
    echo "SSH_PUBLIC_KEY_FILE is not a file: $SSH_PUBLIC_KEY_FILE" >&2
    exit 1
  fi
  PUBLIC_KEY_CONTENT=$(cat "$SSH_PUBLIC_KEY_FILE")
fi

USE_PASSWORD=true
if [[ -n "$PUBLIC_KEY_CONTENT" && -z "$SSH_PASSWORD" ]]; then
  USE_PASSWORD=false
fi

echo "Removing existing container '$CONTAINER_NAME' if present..." >&2
docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

RUN_ENV=(
  -e PUID=1000
  -e PGID=1000
  -e TZ=UTC
  -e USER_NAME="$SSH_USER"
  -e SUDO_ACCESS=true
)

if [[ "$USE_PASSWORD" == true ]]; then
  RUN_ENV+=(-e PASSWORD_ACCESS=true -e USER_PASSWORD="$SSH_PASSWORD")
else
  RUN_ENV+=(-e PASSWORD_ACCESS=false)
fi

if [[ -n "$PUBLIC_KEY_CONTENT" ]]; then
  RUN_ENV+=(-e "PUBLIC_KEY=$PUBLIC_KEY_CONTENT")
fi

echo "Starting $IMAGE as '$CONTAINER_NAME' (host port ${HOST_PORT} -> container 2222)..." >&2
docker run -d \
  --name "$CONTAINER_NAME" \
  "${RUN_ENV[@]}" \
  -p "${HOST_PORT}:2222" \
  "$IMAGE" >/dev/null

BRIDGE_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CONTAINER_NAME")
if [[ -z "$BRIDGE_IP" ]]; then
  echo "failed to read container IP from docker inspect" >&2
  exit 1
fi

echo "Waiting for SSH on 127.0.0.1:${HOST_PORT} ..." >&2
wait_for_tcp 127.0.0.1 "$HOST_PORT" 60

if [[ "$PREFER_CONTAINER_IP" == "1" ]]; then
  # linuxserver/sshd listens on 2222 inside the container (not the host map).
  TEST_SSH_HOST="$BRIDGE_IP"
  TEST_SSH_PORT="2222"
else
  TEST_SSH_HOST="127.0.0.1"
  TEST_SSH_PORT="$HOST_PORT"
fi

# user@host for ssh/scp/rsync (host/port are chosen for host-based access by default)
TEST_SSH_USERHOST="${SSH_USER}@${TEST_SSH_HOST}"

esc_user=$(escape_toml_basic "$SSH_USER")
esc_host=$(escape_toml_basic "$TEST_SSH_HOST")
esc_port=$(escape_toml_basic "$TEST_SSH_PORT")
esc_userhost=$(escape_toml_basic "$TEST_SSH_USERHOST")
esc_bridge=$(escape_toml_basic "$BRIDGE_IP")

{
  echo "# Generated by scripts/docker-ssh-test-up.sh — safe to regenerate."
  echo "TEST_SSH_USER = \"${esc_user}\""
  echo "TEST_SSH_HOST = \"${esc_host}\""
  echo "TEST_SSH_PORT = \"${esc_port}\""
  echo "TEST_SSH_USERHOST = \"${esc_userhost}\""
  echo "TEST_SSH_CONTAINER_BRIDGE_IP = \"${esc_bridge}\""
  echo "TEST_SSH_HOST_PORT = \"$(escape_toml_basic "$HOST_PORT")\""
  if [[ "$USE_PASSWORD" == true ]]; then
    echo "TEST_SSH_PASSWORD = \"$(escape_toml_basic "$SSH_PASSWORD")\""
  fi
} >"$OUTPUT"

echo "Wrote $OUTPUT" >&2
echo "  TEST_SSH_HOST=$TEST_SSH_HOST TEST_SSH_PORT=$TEST_SSH_PORT user=$SSH_USER" >&2
echo "  container bridge IP: $BRIDGE_IP (see TEST_SSH_CONTAINER_BRIDGE_IP; use PREFER_CONTAINER_IP=1 to set TEST_SSH_HOST to it)" >&2
